<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>LogLens.Desktop</AssemblyName>
    <RootNamespace>LogLens.Desktop</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../LogLens.Application/LogLens.Application.csproj" />
    <ProjectReference Include="../LogLens.Infrastructure/LogLens.Infrastructure.csproj" />
  </ItemGroup>
</Project>
